### ISSUE TITLE
Could not locate useful/io__init.class

### ISSUE THREAD

**Issue by jwr** [ninjudd/clojure-protobuf#1]
Hmm. I've just tried to use clojure-protobuf in my project. I followed the instructions on the project page, except I also tried to use version 0.2.10. I only get:

clojure.lang.Compiler$CompilerException: java.io.FileNotFoundException: Could not locate useful/io__init.class or useful/io.clj on classpath:  (tasks.clj:1)
 at clojure.lang.Compiler.eval (Compiler.java:5440)
    clojure.lang.Compiler.eval (Compiler.java:5415)
    clojure.lang.Compiler.load (Compiler.java:5857)
    clojure.lang.RT.loadResourceScript (RT.java:340)
    clojure.lang.RT.loadResourceScript (RT.java:331)
    clojure.lang.RT.load (RT.java:409)
    clojure.lang.RT.load (RT.java:381)
    clojure.core$load$fn__4511.invoke (core.clj:4905)
    clojure.core$load.doInvoke (core.clj:4904)
    clojure.lang.RestFn.invoke (RestFn.java:409)
    clojure.core$load_one.invoke (core.clj:4729)
    clojure.core$load_lib.doInvoke (core.clj:4766)
    clojure.lang.RestFn.applyTo (RestFn.java:143)
    clojure.core$apply.invoke (core.clj:542)
    clojure.core$load_libs.doInvoke (core.clj:4800)
    clojure.lang.RestFn.applyTo (RestFn.java:138)
    clojure.core$apply.invoke (core.clj:542)
    clojure.core$require.doInvoke (core.clj:4869)
    clojure.lang.RestFn.invoke (RestFn.java:409)
    cake.core$eval1503.invoke (project.clj:1)
    clojure.lang.Compiler.eval (Compiler.java:5424)
    clojure.lang.Compiler.eval (Compiler.java:5414)
    clojure.lang.Compiler.load (Compiler.java:5857)
    clojure.lang.Compiler.loadFile (Compiler.java:5820)
    clojure.lang.RT$3.invoke (RT.java:296)
    cake.project$init.invoke (project.clj:29)
    cake.core$start_server.invoke (core.clj:219)
    user$eval925.invoke (NO_SOURCE_FILE:1)
    clojure.lang.Compiler.eval (Compiler.java:5424)
    clojure.lang.Compiler.eval (Compiler.java:5391)
    clojure.core$eval.invoke (core.clj:2382)
    clojure.main$eval_opt.invoke (main.clj:235)
    clojure.main$initialize.invoke (main.clj:254)
    clojure.main$null_opt.invoke (main.clj:279)
    clojure.main$main.doInvoke (main.clj:354)
    clojure.lang.RestFn.invoke (RestFn.java:422)
    clojure.lang.Var.invoke (Var.java:369)
    clojure.lang.AFn.applyToHelper (AFn.java:165)
    clojure.lang.Var.applyTo (Var.java:482)
    clojure.main.main (main.java:37)
Caused by: java.io.FileNotFoundException: Could not locate useful/io__init.class or useful/io.clj on classpath: 
 at clojure.lang.RT.load (RT.java:412)
    clojure.lang.RT.load (RT.java:381)
    clojure.core$load$fn__4511.invoke (core.clj:4905)
    clojure.core$load.doInvoke (core.clj:4904)
    clojure.lang.RestFn.invoke (RestFn.java:409)
    clojure.core$load_one.invoke (core.clj:4729)
    clojure.core$load_lib.doInvoke (core.clj:4766)
    clojure.lang.RestFn.applyTo (RestFn.java:143)
    clojure.core$apply.invoke (core.clj:542)
    clojure.core$load_libs.doInvoke (core.clj:4800)
    clojure.lang.RestFn.applyTo (RestFn.java:138)
    clojure.core$apply.invoke (core.clj:544)
    clojure.core$use.doInvoke (core.clj:4880)
    clojure.lang.RestFn.invoke (RestFn.java:513)
    protobuf.tasks$eval1507$loading__4410__auto____1508.invoke (tasks.clj:1)
    protobuf.tasks$eval1507.invoke (tasks.clj:1)
    clojure.lang.Compiler.eval (Compiler.java:5424)
    clojure.lang.Compiler.eval (Compiler.java:5415)
    clojure.lang.Compiler.load (Compiler.java:5857)
    clojure.lang.RT.loadResourceScript (RT.java:340)
    clojure.lang.RT.loadResourceScript (RT.java:331)
    clojure.lang.RT.load (RT.java:409)
    clojure.lang.RT.load (RT.java:381)
    clojure.core$load$fn__4511.invoke (core.clj:4905)
    clojure.core$load.doInvoke (core.clj:4904)
    clojure.lang.RestFn.invoke (RestFn.java:409)
    clojure.core$load_one.invoke (core.clj:4729)
    clojure.core$load_lib.doInvoke (core.clj:4766)
    clojure.lang.RestFn.applyTo (RestFn.java:143)
    clojure.core$apply.invoke (core.clj:542)
    clojure.core$load_libs.doInvoke (core.clj:4800)
    clojure.lang.RestFn.applyTo (RestFn.java:138)
    clojure.core$apply.invoke (core.clj:542)
    clojure.core$require.doInvoke (core.clj:4869)
    clojure.lang.RestFn.invoke (RestFn.java:409)
    cake.core$eval1503.invoke (project.clj:1)
    clojure.lang.Compiler.eval (Compiler.java:5424)
    clojure.lang.Compiler.eval (Compiler.java:5414)
    clojure.lang.Compiler.load (Compiler.java:5857)
    clojure.lang.Compiler.loadFile (Compiler.java:5820)
    clojure.lang.RT$3.invoke (RT.java:296)
    cake.project$init.invoke (project.clj:29)
    cake.core$start_server.invoke (core.clj:219)
    user$eval925.invoke (NO_SOURCE_FILE:1)
    clojure.lang.Compiler.eval (Compiler.java:5424)
    clojure.lang.Compiler.eval (Compiler.java:5391)
    clojure.core$eval.invoke (core.clj:2382)
    clojure.main$eval_opt.invoke (main.clj:235)
    clojure.main$initialize.invoke (main.clj:254)
    clojure.main$null_opt.invoke (main.clj:279)
    clojure.main$main.doInvoke (main.clj:354)
    clojure.lang.RestFn.invoke (RestFn.java:422)
    clojure.lang.Var.invoke (Var.java:369)
    clojure.lang.AFn.applyToHelper (AFn.java:165)
    clojure.lang.Var.applyTo (Var.java:482)
    clojure.main.main (main.java:37)

Any hints?

**Comment by ninjudd** [comment]
should be fixed now. i was missing a dependency.

thanks

**Comment by jwr** [comment]
Great! Will you upload a new version to Clojars?

**Comment by ninjudd** [comment]
i already did. the version is still 0.2.11-SNAPSHOT

**Comment by jwr** [comment]
And the problem is resolved, thank you!
