### ISSUE TITLE
protobuf java 2.4.1

### ISSUE THREAD

**Issue by andyselv** [ninjudd/clojure-protobuf#10]
The current version of clojure-protobuf doesn't seem to work with protobuf 2.4.1. It appears some of the method signatures have changed in the new version.

P.S. - Thanks for this library! And sorry if I'm mistaken or you already know @ this!

**Comment by ninjudd** [comment]
I'd be happy to accept a patch upgrading to version 2.4.1. Unfortunately, I don't have time to work on this in the near term.

**Comment by ninjudd** [comment]
lein-protobuf now supports specifying the version of Protobuf using:

```
:protobuf-version "2.4.1"
```

I've updated clojure-protobuf to use protobuf 2.4.1, though the default for lein-protobuf is still 2.3.9. Anyway, you can give it a try by updating your `project.clj` to use version `[protobuf "0.6.1-beta1"]`.
