### ISSUE TITLE
Could not locate protobuf__init.class or protobuf.clj

### ISSUE THREAD

**Issue by aphyr** [ninjudd/clojure-protobuf#11]
Hate to open an issue, but I haven't the foggiest idea how to address this and want to leave a record for later googlers. On OS X 10.6.7, clojure 1.2.0, protobuf 0.5.0-beta4, I'm getting an exception from cake test, complaining that protobuf__init isn't on the classpath. Cake _did_ build protoc correctly and successfully compiled my .proto file. I've got some google protobuf classes in my lib dir, but nothing explicitly named "protobuf`__`init.class" or "protobuf.clj". Any ideas?

java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
 at clojure.lang.LazySeq.sval (LazySeq.java:47)
    clojure.lang.LazySeq.seq (LazySeq.java:56)
    clojure.lang.RT.seq (RT.java:450)
    clojure.core$seq.invoke (core.clj:122)
    clojure.core$dorun.invoke (core.clj:2450)
    clojure.core$doall.invoke (core.clj:2465)
    cake.task$run_actions.invoke (task.clj:160)
    cake.task$run_task$fn__1771.invoke (task.clj:202)
    cake.task$run_task.invoke (task.clj:196)
    cake.task$run_task.invoke (task.clj:189)
    cake.main$process_command.invoke (main.clj:30)
    cake.server$create$fn__4133.invoke (server.clj:69)
    cake.utils.server_socket$accept_fn$fn__3868$fn__3871.invoke (server_socket.clj:39)
    cake.utils.server_socket$accept_fn$fn__3868.invoke (server_socket.clj:38)
    clojure.lang.AFn.run (AFn.java:24)
    java.lang.Thread.run (Thread.java:680)
Caused by: java.lang.reflect.InvocationTargetException: null
 at sun.reflect.NativeMethodAccessorImpl.invoke0 (NativeMethodAccessorImpl.java:-2)
    sun.reflect.NativeMethodAccessorImpl.invoke (NativeMethodAccessorImpl.java:39)
    sun.reflect.DelegatingMethodAccessorImpl.invoke (DelegatingMethodAccessorImpl.java:25)
    java.lang.reflect.Method.invoke (Method.java:597)
    classlojure.core$eval_in.doInvoke (core.clj:82)
    clojure.lang.RestFn.applyTo (RestFn.java:143)
    clojure.core$apply.doInvoke (core.clj:548)
    clojure.lang.RestFn.invoke (RestFn.java:534)
    cake.classloader$bake_eval.doInvoke (classloader.clj:165)
    clojure.lang.RestFn.invoke (RestFn.java:440)
    cake.tasks.test$test_vars.invoke (test.clj:159)
    cake.tasks.test$run_project_tests$fn__2808.invoke (test.clj:171)
    cake.classloader$in_bake_ns.invoke (classloader.clj:130)
    cake.tasks.test$run_project_tests.invoke (test.clj:166)
    cake.tasks.test$eval2831$cake_DOT_tasks_DOT_test_test__2833.invoke (test.clj:205)
    cake.task$run_actions$iter__1735__1739$fn__1740$fn__1741.invoke (task.clj:161)
    cake.task$run_actions$iter__1735__1739$fn__1740.invoke (task.clj:160)
    clojure.lang.LazySeq.sval (LazySeq.java:42)
    clojure.lang.LazySeq.seq (LazySeq.java:56)
    clojure.lang.RT.seq (RT.java:450)
    clojure.core$seq.invoke (core.clj:122)
    clojure.core$dorun.invoke (core.clj:2450)
    clojure.core$doall.invoke (core.clj:2465)
    cake.task$run_actions.invoke (task.clj:160)
    cake.task$run_task$fn__1771.invoke (task.clj:202)
    cake.task$run_task.invoke (task.clj:196)
    cake.task$run_task.invoke (task.clj:189)
    cake.main$process_command.invoke (main.clj:30)
    cake.server$create$fn__4133.invoke (server.clj:69)
    cake.utils.server_socket$accept_fn$fn__3868$fn__3871.invoke (server_socket.clj:39)
    cake.utils.server_socket$accept_fn$fn__3868.invoke (server_socket.clj:38)
    clojure.lang.AFn.run (AFn.java:24)
    java.lang.Thread.run (Thread.java:680)
Caused by: clojure.lang.Compiler$CompilerException: java.io.FileNotFoundException: Could not locate protobuf__init.class or protobuf.clj on classpath:  (core.clj:1)
 at clojure.lang.Compiler.eval (Compiler.java:5440)
    clojure.lang.Compiler.load (Compiler.java:5857)
    clojure.lang.RT.loadResourceScript (RT.java:340)
    clojure.lang.RT.loadResourceScript (RT.java:331)
    clojure.lang.RT.load (RT.java:409)
    clojure.lang.RT.load (RT.java:381)
    clojure.core$load$fn__4511.invoke (core.clj:4905)
    clojure.core$load.doInvoke (core.clj:4904)
    clojure.lang.RestFn.invoke (RestFn.java:409)
    clojure.core$load_one.invoke (core.clj:4729)
    clojure.core$load_lib.doInvoke (core.clj:4766)
    clojure.lang.RestFn.applyTo (RestFn.java:143)
    clojure.core$apply.invoke (core.clj:542)
    clojure.core$load_libs.doInvoke (core.clj:4800)
    clojure.lang.RestFn.applyTo (RestFn.java:138)
    clojure.core$apply.invoke (core.clj:544)
    clojure.core$use.doInvoke (core.clj:4880)
    clojure.lang.RestFn.invoke (RestFn.java:409)
    ufold.test.core$eval5848$loading__4410__auto____5849.invoke (core.clj:1)
    ufold.test.core$eval5848.invoke (core.clj:1)
    clojure.lang.Compiler.eval (Compiler.java:5424)
    clojure.lang.Compiler.eval (Compiler.java:5415)
    clojure.lang.Compiler.load (Compiler.java:5857)
    clojure.lang.RT.loadResourceScript (RT.java:340)
    clojure.lang.RT.loadResourceScript (RT.java:331)
    clojure.lang.RT.load (RT.java:409)
    clojure.lang.RT.load (RT.java:381)
    clojure.core$load$fn__4511.invoke (core.clj:4905)
    clojure.core$load.doInvoke (core.clj:4904)
    clojure.lang.RestFn.invoke (RestFn.java:409)
    clojure.core$load_one.invoke (core.clj:4729)
    clojure.core$load_lib.doInvoke (core.clj:4766)
    clojure.lang.RestFn.applyTo (RestFn.java:143)
    clojure.core$apply.invoke (core.clj:542)
    clojure.core$load_libs.doInvoke (core.clj:4800)
    clojure.lang.RestFn.applyTo (RestFn.java:138)
    clojure.core$apply.invoke (core.clj:542)
    clojure.core$require.doInvoke (core.clj:4869)
    clojure.lang.RestFn.invoke (RestFn.java:409)
    bake.test$test_vars$fn__312.invoke (test.clj:26)
    clojure.core$r.invoke (core.clj:799)
    bake.test$test_vars.invoke (test.clj:25)
    clojure.lang.AFn.applyToHelper (AFn.java:165)
    clojure.lang.AFn.applyTo (AFn.java:151)
    clojure.core$apply.invoke (core.clj:540)
    bake4293$eval5842$fn__5843.invoke (NO_SOURCE_FILE:0)
    sun.reflect.NativeMethodAccessorImpl.invoke0 (NativeMethodAccessorImpl.java:-2)
    sun.reflect.NativeMethodAccessorImpl.invoke (NativeMethodAccessorImpl.java:39)
    sun.reflect.DelegatingMethodAccessorImpl.invoke (DelegatingMethodAccessorImpl.java:25)
    java.lang.reflect.Method.invoke (Method.java:597)
    classlojure.core$eval_in.doInvoke (core.clj:82)
    clojure.lang.RestFn.applyTo (RestFn.java:143)
    clojure.core$apply.doInvoke (core.clj:548)
    clojure.lang.RestFn.invoke (RestFn.java:534)
    cake.classloader$bake_eval.doInvoke (classloader.clj:165)
    clojure.lang.RestFn.invoke (RestFn.java:440)
    cake.tasks.test$test_vars.invoke (test.clj:159)
    cake.tasks.test$run_project_tests$fn__2808.invoke (test.clj:171)
    cake.classloader$in_bake_ns.invoke (classloader.clj:130)
    cake.tasks.test$run_project_tests.invoke (test.clj:166)
    cake.tasks.test$eval2831$cake_DOT_tasks_DOT_test_test__2833.invoke (test.clj:205)
    cake.task$run_actions$iter__1735__1739$fn__1740$fn__1741.invoke (task.clj:161)
    cake.task$run_actions$iter__1735__1739$fn__1740.invoke (task.clj:160)
    clojure.lang.LazySeq.sval (LazySeq.java:42)
    clojure.lang.LazySeq.seq (LazySeq.java:56)
    clojure.lang.RT.seq (RT.java:450)
    clojure.core$seq.invoke (core.clj:122)
    clojure.core$dorun.invoke (core.clj:2450)
    clojure.core$doall.invoke (core.clj:2465)
    cake.task$run_actions.invoke (task.clj:160)
    cake.task$run_task$fn__1771.invoke (task.clj:202)
    cake.task$run_task.invoke (task.clj:196)
    cake.task$run_task.invoke (task.clj:189)
    cake.main$process_command.invoke (main.clj:30)
    cake.server$create$fn__4133.invoke (server.clj:69)
    cake.utils.server_socket$accept_fn$fn__3868$fn__3871.invoke (server_socket.clj:39)
    cake.utils.server_socket$accept_fn$fn__3868.invoke (server_socket.clj:38)
    clojure.lang.AFn.run (AFn.java:24)
    java.lang.Thread.run (Thread.java:680)
Caused by: java.io.FileNotFoundException: Could not locate protobuf__init.class or protobuf.clj on classpath: 
 at clojure.lang.RT.load (RT.java:412)
    clojure.lang.RT.load (RT.java:381)
    clojure.core$load$fn__4511.invoke (core.clj:4905)
    clojure.core$load.doInvoke (core.clj:4904)
    clojure.lang.RestFn.invoke (RestFn.java:409)
    clojure.core$load_one.invoke (core.clj:4729)
    clojure.core$load_lib.doInvoke (core.clj:4766)
    clojure.lang.RestFn.applyTo (RestFn.java:143)
    clojure.core$apply.invoke (core.clj:542)
    clojure.core$load_libs.doInvoke (core.clj:4800)
    clojure.lang.RestFn.applyTo (RestFn.java:138)
    clojure.core$apply.invoke (core.clj:544)
    clojure.core$use.doInvoke (core.clj:4880)
    clojure.lang.RestFn.invoke (RestFn.java:409)
    ufold.core$eval5860.invoke (core.clj:5)
    clojure.lang.Compiler.eval (Compiler.java:5424)
    clojure.lang.Compiler.load (Compiler.java:5857)
    clojure.lang.RT.loadResourceScript (RT.java:340)
    clojure.lang.RT.loadResourceScript (RT.java:331)
    clojure.lang.RT.load (RT.java:409)
    clojure.lang.RT.load (RT.java:381)
    clojure.core$load$fn__4511.invoke (core.clj:4905)
    clojure.core$load.doInvoke (core.clj:4904)
    clojure.lang.RestFn.invoke (RestFn.java:409)
    clojure.core$load_one.invoke (core.clj:4729)
    clojure.core$load_lib.doInvoke (core.clj:4766)
    clojure.lang.RestFn.applyTo (RestFn.java:143)
    clojure.core$apply.invoke (core.clj:542)
    clojure.core$load_libs.doInvoke (core.clj:4800)
    clojure.lang.RestFn.applyTo (RestFn.java:138)
    clojure.core$apply.invoke (core.clj:544)
    clojure.core$use.doInvoke (core.clj:4880)
    clojure.lang.RestFn.invoke (RestFn.java:409)
    ufold.test.core$eval5848$loading__4410__auto____5849.invoke (core.clj:1)
    ufold.test.core$eval5848.invoke (core.clj:1)
    clojure.lang.Compiler.eval (Compiler.java:5424)
    clojure.lang.Compiler.eval (Compiler.java:5415)
    clojure.lang.Compiler.load (Compiler.java:5857)
    clojure.lang.RT.loadResourceScript (RT.java:340)
    clojure.lang.RT.loadResourceScript (RT.java:331)
    clojure.lang.RT.load (RT.java:409)
    clojure.lang.RT.load (RT.java:381)
    clojure.core$load$fn__4511.invoke (core.clj:4905)
    clojure.core$load.doInvoke (core.clj:4904)
    clojure.lang.RestFn.invoke (RestFn.java:409)
    clojure.core$load_one.invoke (core.clj:4729)
    clojure.core$load_lib.doInvoke (core.clj:4766)
    clojure.lang.RestFn.applyTo (RestFn.java:143)
    clojure.core$apply.invoke (core.clj:542)
    clojure.core$load_libs.doInvoke (core.clj:4800)
    clojure.lang.RestFn.applyTo (RestFn.java:138)
    clojure.core$apply.invoke (core.clj:542)
    clojure.core$require.doInvoke (core.clj:4869)
    clojure.lang.RestFn.invoke (RestFn.java:409)
    bake.test$test_vars$fn__312.invoke (test.clj:26)
    clojure.core$r.invoke (core.clj:799)
    bake.test$test_vars.invoke (test.clj:25)
    clojure.lang.AFn.applyToHelper (AFn.java:165)
    clojure.lang.AFn.applyTo (AFn.java:151)
    clojure.core$apply.invoke (core.clj:540)
    bake4293$eval5842$fn__5843.invoke (NO_SOURCE_FILE:0)
    sun.reflect.NativeMethodAccessorImpl.invoke0 (NativeMethodAccessorImpl.java:-2)
    sun.reflect.NativeMethodAccessorImpl.invoke (NativeMethodAccessorImpl.java:39)
    sun.reflect.DelegatingMethodAccessorImpl.invoke (DelegatingMethodAccessorImpl.java:25)
    java.lang.reflect.Method.invoke (Method.java:597)
    classlojure.core$eval_in.doInvoke (core.clj:82)
    clojure.lang.RestFn.applyTo (RestFn.java:143)
    clojure.core$apply.doInvoke (core.clj:548)
    clojure.lang.RestFn.invoke (RestFn.java:534)
    cake.classloader$bake_eval.doInvoke (classloader.clj:165)
    clojure.lang.RestFn.invoke (RestFn.java:440)
    cake.tasks.test$test_vars.invoke (test.clj:159)
    cake.tasks.test$run_project_tests$fn__2808.invoke (test.clj:171)
    cake.classloader$in_bake_ns.invoke (classloader.clj:130)
    cake.tasks.test$run_project_tests.invoke (test.clj:166)
    cake.tasks.test$eval2831$cake_DOT_tasks_DOT_test_test__2833.invoke (test.clj:205)
    cake.task$run_actions$iter__1735__1739$fn__1740$fn__1741.invoke (task.clj:161)
    cake.task$run_actions$iter__1735__1739$fn__1740.invoke (task.clj:160)
    clojure.lang.LazySeq.sval (LazySeq.java:42)
    clojure.lang.LazySeq.seq (LazySeq.java:56)
    clojure.lang.RT.seq (RT.java:450)
    clojure.core$seq.invoke (core.clj:122)
    clojure.core$dorun.invoke (core.clj:2450)
    clojure.core$doall.invoke (core.clj:2465)
    cake.task$run_actions.invoke (task.clj:160)
    cake.task$run_task$fn__1771.invoke (task.clj:202)
    cake.task$run_task.invoke (task.clj:196)
    cake.task$run_task.invoke (task.clj:189)
    cake.main$process_command.invoke (main.clj:30)
    cake.server$create$fn__4133.invoke (server.clj:69)
    cake.utils.server_socket$accept_fn$fn__3868$fn__3871.invoke (server_socket.clj:39)
    cake.utils.server_socket$accept_fn$fn__3868.invoke (server_socket.clj:38)
    clojure.lang.AFn.run (AFn.java:24)
    java.lang.Thread.run (Thread.java:680)

**Comment by ninjudd** [comment]
@aphyr, you figured this out, right? If not, please reopen.
