### ISSUE TITLE
Password prompt only reads one keypress.

### ISSUE THREAD

**Issue by rryan** [ninjudd/clojure-protobuf#19]
OS: Ubuntu Lucid 10.04
Shell: zsh

While building and installing protoc, the password prompt (via System.console.readPassword) only reads one character. It then tries to sudo using the 1 character (which fails).

**Comment by ninjudd** [comment]
@Raynes, is this fixed with the new lein version of protobuf?

**Comment by Raynes** [comment]
I just tried this myself and it seems to work fine. I tested both installing and uninstalling.

``` shell
68-245-171-115% zsh --version
zsh 4.3.11 (i386-apple-darwin11.0)
```

`System.console.readPassword` is only used in the new lein version, so it isn't 'fixed' in the lein version, but it doesn't actually seem to be broken.

@rryan  What version of zsh are you using and what particular version of clojure-protobuf?

**Comment by ninjudd** [comment]
We should probably move to having users install protobuf on their own using whatever package manager is appropriate for their system (brew, yum, etc...) I'll create a separate ticket for that.

**Comment by Raynes** [comment]
@ninjudd Don't we rely on files from the release distribution?

**Comment by ninjudd** [comment]
Let's discuss issues with that approach in #34.
