### ISSUE TITLE
Could not locate cake/file.clj

### ISSUE THREAD

**Issue by jwr** [ninjudd/clojure-protobuf#2]
clojure.lang.Compiler$CompilerException: java.io.FileNotFoundException: Could not locate cake/file__init.class or cake/file.clj on classpath:  (tasks.clj:1)

This is with 0.2.11-SNAPSHOT. I can't move to 0.2.10, because that one can't find the "useful" package.

**Comment by jwr** [comment]
btw, I am using cake 0.4.18

**Comment by ninjudd** [comment]
upgrading to the new version of cake (git master 0.5.0-SNAPSHOT) should fix this. I plan to release it as a gem later this week

**Comment by jwr** [comment]
Ahem... is there an easy way to use that version right now?

Sorry for bothering you, but because of clojure-protobuf we switched to using cake and we use it to build and release our software. So we've become dependent on both cake and clojure-protobuf and least not breaking...

**Comment by ninjudd** [comment]
You can use the third installation method in the README at http://github.com/ninjudd/cake

If that isn't possible for you, I can probably push the timetable and release 0.5.0 later today.

**Comment by jwr** [comment]
Sorry, I should have looked better. I'll just do that, then.

If you get the new version released tomorrow afternoon (meaning around this time of day), that would be great, as my coworkers will simply use that.

thanks!

**Comment by jwr** [comment]
Ok, just wanted to report -- it took a cleaning of my ~/.m2 repository, but I finally managed to get cake and clojure-protobuf to work well together. The current git version of cake and clojure-protobuf-0.2.11-SNAPSHOT as of now work for me.

Looking forward to versioned releases! Thanks again.
