### ISSUE TITLE
add development/testing instructions

### ISSUE THREAD

**Issue by reiddraper** [ninjudd/clojure-protobuf#20]
I think it's something along the lines of:

``` bash
lein protobuf compile
lein test
```

**Comment by reiddraper** [comment]
wrong repo, apologies.

**Comment by ninjudd** [comment]
@Raynes, why can't lein make sure compile is always run before test?

**Comment by Raynes** [comment]
@ninjudd The best I can do is provide a hook around test that runs `compile`. I think @technomancy talked to you about some global 'always run this' list that it might be possible to add tasks to? If so, we might be able to do that.

The problem with hooks is that the user has to specify them in his project.clj in order for them to work in his project.

**Comment by technomancy** [comment]
https://github.com/technomancy/leiningen/blob/master/leiningen-core/src/leiningen/core/eval.clj#L58

This should be easier in Leiningen 2 with prep-tasks.

However, you'll still have to supply a hook to populate the prep-tasks
atom. I'm still thinking through a way to allow auto-discover hooks from
plugins; would be happy to have some discussion on how that would work.

**Comment by ninjudd** [comment]
I think project middleware would be a good solution to this.

**Comment by technomancy** [comment]
I've just pushed out an implementation of project middleware as well as moving prep-tasks into the project map. So now users can add :prep-tasks ["protobuf"] to project.clj and have it run before every eval-in-project. In the future, autodetected middlewares could remove the need for any changes to project.clj.
