### ISSUE TITLE
protofields does not remap _ to -

### ISSUE THREAD

**Issue by jwr** [ninjudd/clojure-protobuf#3]
protofields does not do the cool renaming trick:
        String name = ((String) key).replaceAll("-","_");

I expected protofields to return field names with underscores converted to hyphens.

this bit me, because I need to construct a full map with defaults filled in (please consider adding this in clojure-protobuf):

  (defn- fill-default-fields [cfg](let [all-keys %28keys %28protofields CustomerConfig%29%29]
      %28merge %28apply hash-map %28interleave all-keys %28map #%28protodefault CustomerConfig %%29 all-keys%29%29%29 cfg%29))

**Comment by ninjudd** [comment]
just fixed this in 0.3.0-SNAPSHOT.

thanks
