### ISSUE TITLE
Stop compiling protoc from source

### ISSUE THREAD

**Issue by ninjudd** [ninjudd/clojure-protobuf#34]
Instead of compiling `protoc` from source, we should have users install protobuf using the package manager for their OS (brew, yum, etc...).

We may still have to download the Java source though, right @Raynes.

**Comment by Raynes** [comment]
It looks like we extract some protos from the source distribution for our top-level protobuf project itself, so this isn't something we'll need to do for an end-user.

**Comment by ninjudd** [comment]
Great. So we can only download the source when building clojure-protobuf itself.

We should have a good error message for the user when `protoc` is not available though. Something like:

```
Could not find protoc on your path. You need to install it using your favorite package manager.
Try one of the following:
    brew install protobuf
    yum install protobuf
Or install it from source: http://code.google.com/p/protobuf/downloads/list
```

**Comment by ninjudd** [comment]
We changed our minds about this. Instead, we still compile `protoc` from source, we just don't install it using `sudo`.
