### ISSUE TITLE
pom.xml has reference to snapshot builds of clojure and clojure-contrib

### ISSUE THREAD

**Issue by jholmberg-cni** [ninjudd/clojure-protobuf#4]
Hi,
I've been interested in using clojure-protobuf with a project I'm currently working on. So I decided to get it using lein. I kept getting the following errors however when I ran lein deps:
## Unable to resolve artifact: Missing:

1) org.clojure:clojure:jar:1.2.0-master-SNAPSHOT

  Try downloading the file manually from the project website.

  Then, install it using the command: 
      mvn install:install-file -DgroupId=org.clojure -DartifactId=clojure -Dversion=1.2.0-master-SNAPSHOT -Dpackaging=jar -Dfile=/path/to/file

  Alternatively, if you host your own repository you can deploy the file there: 
      mvn deploy:deploy-file -DgroupId=org.clojure -DartifactId=clojure -Dversion=1.2.0-master-SNAPSHOT -Dpackaging=jar -Dfile=/path/to/file -Durl=[url] -DrepositoryId=[id]

  Path to dependency: 
    1) org.apache.maven:super-pom:jar:2.0
    2) clojure-protobuf:clojure-protobuf:jar:0.2.4
    3) org.clojure:clojure:jar:1.2.0-master-SNAPSHOT

2) org.clojure:clojure-contrib:jar:1.2.0-SNAPSHOT

  Try downloading the file manually from the project website.

  Then, install it using the command: 
      mvn install:install-file -DgroupId=org.clojure -DartifactId=clojure-contrib -Dversion=1.2.0-SNAPSHOT -Dpackaging=jar -Dfile=/path/to/file

  Alternatively, if you host your own repository you can deploy the file there: 
      mvn deploy:deploy-file -DgroupId=org.clojure -DartifactId=clojure-contrib -Dversion=1.2.0-SNAPSHOT -Dpackaging=jar -Dfile=/path/to/file -Durl=[url] -DrepositoryId=[id]

  Path to dependency: 
    1) org.apache.maven:super-pom:jar:2.0
    2) clojure-protobuf:clojure-protobuf:jar:0.2.4
    3) org.clojure:clojure-contrib:jar:1.2.0-SNAPSHOT

I downloaded the jar and took a peek at the META-INF/maven/clojure-protobuf/clojure-protobuf/pom.xml file and noticed that it was referencing clojure 1.2.0-master-SNAPSHOT and clojure-contrib 1.2.0-SNAPSHOT.

I was wondering if it would be better to just refer to the 1.2.0 versions of these libraries instead.

**Comment by jholmberg-cni** [comment]
Follow up to this. Just noticed that this was the case in 0.2.4 but looks like things are working just fine in 0.2.11.
Thanks!

**Comment by ninjudd** [comment]
Thanks. I removed the reference to 0.2.4 in the README and made a note to check for the latest version.
