### ISSUE TITLE
Feature request: read protobufs from input streams

### ISSUE THREAD

**Issue by nathell** [ninjudd/clojure-protobuf#5]
This would really help me -- I have a structure defined using protobufs and want to create a function similar to read-lines (i.e., one accepting an input stream and returning a lazy seq of protobuf-decoded structures, of which there could be more than can coexist in memory at a time).

Would it be possible to add this?

**Comment by ninjudd** [comment]
i just checked in a first pass at implementing this. i used the google protobuf methods writeDelimitedTo and mergeDelimitedFrom, which prefix each message in the stream with a length. check out the test i added for an example of usage.

**Comment by ninjudd** [comment]
the relevant methods are `write-protobuf` and `protobuf-seq`
