### ISSUE TITLE
protobuf-seq should close the stream after the sequence is consumed

### ISSUE THREAD

**Issue by jwr** [ninjudd/clojure-protobuf#6]
Just like, say, read-lines in clojure.contrib.io. Otherwise, it isn't very useful in real life, because you need to hold on to the stream and babysit it (and remember to close it) until you consume the sequence. Or read it all in one go, which defeats the purpose of using protobuf-seq in the first place.

**Comment by ninjudd** [comment]
Good point. I'd be happy to accept a patch to fix this.

**Comment by jwr** [comment]
Ah, sorry, I should have submitted a pull request right away. I've done that now: https://github.com/ninjudd/clojure-protobuf/pull/7

**Comment by ninjudd** [comment]
https://github.com/flatland/clojure-protobuf/pull/7
